### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
x-token: CaioToken
x-key: CaioKey
### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
x-token: CaioToken
x-key: CaioKey
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
x-token: CaioToken
x-key: CaioKey
content-type: application/json

{
"nome" : "ABC Bolinhas my G",
"descricao" : "texto de descricao generico do teste",
"foto" : "4912991",
"valor_unitario" : 20
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
x-token: CaioToken
x-key: CaioKey
content-type: application/json

{
"nome" : "ABC Bolinhas my G porem editei ele",
"descricao" : "texto de descricao generico do teste",
"foto" : "4912991",
"valor_unitario" : 20
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1
x-token: CaioToken
x-key: CaioKey